2024-03-03 14:23:02,161:DEBUG:certbot._internal.main:certbot version: 2.9.0
2024-03-03 14:23:02,161:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-03-03 14:23:02,161:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/html', '--email', 'yehtetag.y@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'ykvideo.org', '-d', 'www.ykvideo.org']
2024-03-03 14:23:02,162:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-03-03 14:23:02,186:DEBUG:certbot._internal.log:Root logging level set at 30
2024-03-03 14:23:02,188:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-03-03 14:23:02,188:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fe196333080>
Prep: True
2024-03-03 14:23:02,189:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fe196333080> and installer None
2024-03-03 14:23:02,189:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-03-03 14:23:02,261:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1599810837', new_authzr_uri=None, terms_of_service=None), 563288dc75aec3378973e4e4782eb5f2, Meta(creation_dt=datetime.datetime(2024, 3, 3, 13, 2, 4, tzinfo=<UTC>), creation_host='8d7fb3772c13', register_to_eff=None))>
2024-03-03 14:23:02,262:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-03-03 14:23:02,265:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-03-03 14:23:02,941:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2024-03-03 14:23:02,942:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 03 Mar 2024 14:23:02 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "3_qEuv3ys7c": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-02/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-03-03 14:23:02,959:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
2024-03-03 14:23:03,251:DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
2024-03-03 14:23:03,252:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/archive/ykvideo.org/cert1.pem is signed by the certificate's issuer.
2024-03-03 14:23:03,253:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/archive/ykvideo.org/cert1.pem is: OCSPCertStatus.GOOD
2024-03-03 14:23:03,258:DEBUG:certbot._internal.display.obj:Notifying user: Certificate not yet due for renewal
2024-03-03 14:23:03,259:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1593, in certonly
    should_get_cert, lineage = _find_cert(config, domains, certname)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 363, in _find_cert
    action, lineage = _find_lineage_for_domains_and_certname(config, domains, certname)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 393, in _find_lineage_for_domains_and_certname
    return _find_lineage_for_domains(config, domains)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 338, in _find_lineage_for_domains
    return _handle_identical_cert_request(config, ident_names_cert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 289, in _handle_identical_cert_request
    response = display_util.menu(question, choices,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 80, in menu
    return obj.get_display().menu(message, choices, default=default, cli_flag=cli_flag,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 125, in menu
    code, selection = self._get_valid_int_ans(len(choices))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 390, in _get_valid_int_ans
    ans = util.input_with_timeout(input_msg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/display/util.py", line 68, in input_with_timeout
    raise EOFError
EOFError
2024-03-03 14:23:03,262:ERROR:certbot._internal.log:An unexpected error occurred:
2024-03-03 14:23:03,263:ERROR:certbot._internal.log:EOFError
